spring:
  application:
    name: cutter
  threads:
    virtual:
      enabled: false
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 20GB

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 1000

local-storage:
  location: /files
